### PR TITLE
Excluded internal links starting with "@"

### PR DESCRIPTION
**Pull request by MatonAnthony**
Ported from https://github.com/Elchi3/mdn-doc-tests/pull/226

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
That if condition! wow :D

It could be more explanatory if these things would be booleans beforehands and then several booleans would be checked in that if...

This works, though.

**Comment by MatonAnthony** [comment]
I can refactor it if you want.
An other way to make it more readable could be this

```javascript
if (linkLocale && 
    !linkLocale.startsWith("@") &&
    linkLocale.toLowerCase() !== pageLocale.toLowerCase() &&
    (!linkDomain || linkDomain === pageDomain)
  ) 
{
```

**Comment by Elchi3** [comment]
Yeah, by storing into a bool before I thought it could make the intent more clear:

```
let oldAttachmentLink = linkLocale.startsWith("@");
if (linkLocale && !oldAttachmentLink && someOtherThing && moreThings) {
  foo;
}
```

**Comment by Elchi3** [comment]
Yes \o/
r+

**Pull request merged**
